import { Inter } from "next/font/google";
import 'react-toastify/dist/ReactToastify.css';
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import "./index.css";
import Nav from "./(components)/Nav/Nav";
import { ToastContainer } from "react-toastify";
import Offlines from "./(components)/Offlines/Offlines";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Plog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed top-0 -z-10 w-full h-full bg-red-500">
          <div className="absolute inset-0 -z-10 h-full w-full items-center px-5 py-24 [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)]"></div>
        </div>
        <Nav />
        {children}
        <ToastContainer />
        <Offlines />
      </body>
    </html>
  );
}
